---
title: "Validation Figures"
author: "Weihsueh Chiu"
date: "`r format(Sys.time(), '%F')`"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(coda)
library(bayesplot) 
library(ggplot2)
library(stringr)
library(knitr)
library(ggpubr)
library(dplyr)
library(metR)
library(data.table)
library(usmap)
knitr::opts_chunk$set(echo = TRUE, dpi = 300, fig.height=6, fig.width=6,message = FALSE,warning=FALSE)
functiondir <- "../functions"
modeldir <- "../model"
datezero <- "2019-12-31"
source(file.path(functiondir,"get_reopendata_function.R"))
```

## Prediction Run

Calibration using data through July 22.

```{r load prediction results, echo=FALSE, include=FALSE}

# Separately source "run_plot_validation.2_scenario.R")

folder <- "../SEIR.reopen.state.2020.07.22"
fips_table <- read.csv(file.path(folder,"FIPS_TABLE.csv"),colClasses=c(
  rep("character",4),rep("numeric",2)
))
rownames(fips_table) <- fips_table$Alpha.code
fips_table$Region <- "South"
fips_table$Region[fips_table$Alpha.code %in% c("CT","ME","MA","NH","RI",
                                               "VT","NJ","NY","PA")] <- "Northeast"
fips_table$Region[fips_table$Alpha.code %in% c("IL","IN","MI","OH","WI","IA",
                                               "KS","MN","MO","NE","ND","SD")] <- "Midwest"
fips_table$Region[fips_table$Alpha.code %in% c("AZ","CO","ID","MT","NV","NM","UT","WY",
                                               "AK","CA","HI","OR","WA")] <- "West"

statesarr <- fips_table$Alpha.code[2:52]
## Read prediction files
allcalvaldat <- data.frame()
for (statenow in statesarr) { 
  csvfile <- list.files(path=file.path(folder,statenow),
                           pattern="*prediction.quantiles.csv",
                         full.names=TRUE)
  calvaldat <- read.csv(csvfile,as.is=TRUE)
  calvaldat$state <- statenow
  allcalvaldat <- rbind(allcalvaldat,calvaldat)
}
allcalvaldat$Output_Var[allcalvaldat$Output_Var=="N_pos"] <- "positiveIncrease"
allcalvaldat$Output_Var[allcalvaldat$Output_Var=="D_pos"] <- "deathIncrease"
allcalvaldat$Output_Var[allcalvaldat$Output_Var=="CumPos"] <- "positive"
allcalvaldat$Output_Var[allcalvaldat$Output_Var=="D_T"] <- "death"
allcalvaldat$Date <- as.Date(allcalvaldat$Time,origin=as.Date(datezero))

## Read data files
alldat.df <- read.csv(file.path(folder,"DAILYTESTDATA.csv"))
alldat.df$Date <- as.Date(alldat.df$numDate,origin=as.Date(datezero))
names(alldat.df)[names(alldat.df)=="variable"] <- "Output_Var"
names(alldat.df)[names(alldat.df)=="value"] <- "Data"

allcumdat.df <- read.csv(file.path(folder,"CUMULTESTDATA.csv"))
allcumdat.df$Date <- as.Date(allcumdat.df$numDate,origin=as.Date(datezero))
names(allcumdat.df)[names(allcumdat.df)=="variable"] <- "Output_Var"
names(allcumdat.df)[names(allcumdat.df)=="value"] <- "Data"

```

Example states: one from each major region of the US: New York (Northeast), Ohio (Midwest), Texas (South), and Washington (West).

```{r prediction example states, echo=FALSE, fig.height=4.87,fig.width=8}
egstates <- c("OH","NY","TX","WA")
calvaldat.df <- subset(allcalvaldat,state %in% egstates)

## Observed/predicted daily
obsdat.df<-subset(alldat.df,state %in% egstates & (
  Output_Var == "positiveIncrease" | Output_Var == "deathIncrease"
)) 

## Calibration vs. validation
datadatemax <- "2020-07-22"
novalid <- FALSE
validdate <- "2020-07-22"
obsdat.df$Calibration <- obsdat.df$Date <= datadatemax
calvaldat.df$Calibration <- calvaldat.df$Date <= datadatemax
obsdat.df$Calibration <- factor(ifelse(obsdat.df$Calibration,
                                       "Train","Validate"),
                                levels=c("Train","Validate"))

calvaldat.df$Calibration <- factor(ifelse(calvaldat.df$Calibration,
                                        "Train","Validate"),
                                levels=c("Train","Validate"))

if (novalid) {
  obsdat.df <- subset(obsdat.df,Date <= as.Date(datadatemax))
  calvaldat.df <- subset(calvaldat.df,Date <= as.Date(datadatemax))
} else {
  obsdat.df <- subset(obsdat.df,Date <= as.Date(validdate))
  calvaldat.df <- subset(calvaldat.df,Date <= as.Date(validdate))
}
obsnames <- c("Daily reported cases","Daily confirmed deaths")
names(obsnames) <- c("positiveIncrease","deathIncrease")

calvaldat.df$Prediction.2.5.[calvaldat.df$Prediction.2.5.<0.1]<-0.1
calvaldat.df$Prediction.25.[calvaldat.df$Prediction.25.<0.1]<-0.1
calvaldat.df$Prediction.50.[calvaldat.df$Prediction.50.<0.1]<-0.1
calvaldat.df$Prediction.75.[calvaldat.df$Prediction.75.<0.1]<-0.1
calvaldat.df$Prediction.97.5.[calvaldat.df$Prediction.97.5.<0.1]<-0.1

p<-ggplot(subset(calvaldat.df,Output_Var=="positiveIncrease" | Output_Var=="deathIncrease"))+
  geom_col(aes(x=Date,y=Data,fill=""),alpha=0.8,data=obsdat.df)+
  geom_ribbon(aes(x=Date,ymin=Prediction.2.5.,ymax=Prediction.97.5.,
                  fill="CrI"),alpha=0.8)+
  geom_ribbon(aes(x=Date,ymin=Prediction.25.,ymax=Prediction.75.,
                  fill="IQR"),alpha=0.8)+
  geom_line(aes(x=Date,y=Prediction.50.,linetype="Median"))+
  ylab("")+scale_fill_viridis_d(option="magma",begin = 0.2,end=0.95) +
  scale_x_date(date_minor_breaks = "1 day")+
  facet_wrap(~Output_Var*state,ncol=4,
                  labeller = labeller(Output_Var = obsnames),
                scales="free_y")+
  theme_bw()+theme(legend.position = "bottom",
                   legend.title = element_text(size = 8),
                    legend.text = element_text(size = 8),
                   strip.text = element_text(size=10,
                                             margin = 
                                               margin(.05, 0, .05, 0, "cm"))) + 
        labs(fill="",linetype="Prediction")+
        guides(
         linetype = guide_legend(order = 1),
         fill = guide_legend(order = 2,nrow=1))


print(p)
ggsave("FigS5.pdf",plot=p,height=4.5,width=13,scale=0.8)
# ggsave("FigS5.png",plot=p,height=4.5,width=13,scale=1.1)
# ggsave("FigS5.jpeg",plot=p,height=4.5,width=13,scale=1.1)

```

```{r scatter plot full pred, echo=FALSE, fig.height=3.5}
preddat.df <- allcalvaldat

## Observed/predicted daily
obsdat.df<-subset(alldat.df,
  Output_Var == "positiveIncrease" | Output_Var == "deathIncrease"
)

## Calibration vs. validation
datadatemax <- "2020-07-22"
novalid <- TRUE
validdate <- "2020-07-22"
if (novalid) {
  obsdat.df <- subset(obsdat.df,Date <= as.Date(datadatemax))
  preddat.df <- subset(preddat.df,Date <= as.Date(datadatemax))
} else {
  obsdat.df <- subset(obsdat.df,Date <= as.Date(validdate))
  preddat.df <- subset(preddat.df,Date <= as.Date(validdate))
}
obsnames <- c("Daily reported cases","Daily confirmed deaths")
names(obsnames) <- c("positiveIncrease","deathIncrease")

predobs.df <- merge(obsdat.df,preddat.df,all.x=TRUE)

likeCIdeath <- data.frame(Data=c(0.1,0.3,seq(1,
                                   max(subset(predobs.df,
                                              Output_Var=="deathIncrease"
                                              )$Data)),1000,3000,10000,50000))
likeCIdeath$Prediction.50. <- likeCIdeath$Data
likeCIdeath$Prediction.2.5. <- qnbinom(0.025,size=8,
                                       prob=8/(8+likeCIdeath$Data))
likeCIdeath$Prediction.97.5. <- qnbinom(0.975,size=8,
                                       prob=8/(8+likeCIdeath$Data))
likeCIdeath$Output_Var<-"deathIncrease"

likeCIpositive <- data.frame(Data=c(0.1,0.3,seq(1,
                                   max(subset(predobs.df,
                                              Output_Var=="positiveIncrease"
                                              )$Data)),50000))
likeCIpositive$Prediction.50. <- likeCIpositive$Data
likeCIpositive$Prediction.2.5. <- qnbinom(0.025,size=4,
                                       prob=4/(4+likeCIpositive$Data))
likeCIpositive$Prediction.97.5. <- qnbinom(0.975,size=4,
                                       prob=4/(4+likeCIpositive$Data))
likeCIpositive$Output_Var<-"positiveIncrease"
likeCI<-rbind(likeCIpositive,likeCIdeath)

FigS6<-ggplot(predobs.df)+
  geom_pointrange(aes(x=Data,y=Prediction.50.,
                      ymin=Prediction.2.5.,
                      ymax=Prediction.97.5.,
                      color=state,group=state),
                  position=position_jitter(width=0.1))+
  geom_ribbon(data=likeCI,
              aes(x=Data,ymin=Prediction.2.5.,
                      ymax=Prediction.97.5.,fill="CrI"),alpha=0.4)+
  geom_abline(slope=1,intercept=0)+
  scale_fill_viridis_d(option="magma",begin = 0.95,end=0.95)+
  scale_color_viridis_d()+
  coord_cartesian(xlim=c(0.1,50000),ylim=c(0.1,50000))+
  scale_x_log10()+
  scale_y_log10()+facet_grid(~Output_Var,labeller = labeller(Output_Var=obsnames))+
  ylab("Prediction (95% CrI)")+guides(fill = "none")+
  theme_bw()+
  annotation_logticks()
print(FigS6)
ggsave("FigS6.pdf",plot=FigS6,height=3.5,width=8,scale=1.5)
ggsave("FigS6.jpeg",plot=FigS6,height=3.5,width=8,scale=1.5)
```

