---
title: "Scenario prediction figures"
author: "Weihsueh Chiu"
date: "`r format(Sys.time(), '%F')`"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(coda)
library(bayesplot) 
library(ggplot2)
library(stringr)
library(knitr)
library(ggpubr)
library(dplyr)
library(tidyr)
library(metR)
library(data.table)
library(usmap)
knitr::opts_chunk$set(echo = TRUE, dpi = 300, fig.height=6, fig.width=6,message = FALSE,warning=FALSE)
functiondir <- "../functions"
modeldir <- "../model"
datezero <- "2019-12-31"
source(file.path(functiondir,"get_reopendata_function.R"))
```

## Load data

```{r load scenarios, echo=FALSE}

folder <- "../SEIR.reopen.state.2020.07.22"
alldat.df <- read.csv(file.path(folder,"DAILYTESTDATA.csv"))
alldat.df$Date <- as.Date(alldat.df$numDate,origin=as.Date(datezero))
names(alldat.df)[names(alldat.df)=="variable"] <- "Output_Var"
names(alldat.df)[names(alldat.df)=="value"] <- "Data"

allcumdat.df <- read.csv(file.path(folder,"CUMULTESTDATA.csv"))
allcumdat.df$Date <- as.Date(allcumdat.df$numDate,origin=as.Date(datezero))
names(allcumdat.df)[names(allcumdat.df)=="variable"] <- "Output_Var"
names(allcumdat.df)[names(allcumdat.df)=="value"] <- "Data"

datadatestart<-"2020-03-01"
preddateend<-"2020-09-30"
fips_table <- read.csv(file.path(folder,"FIPS_TABLE.csv"),colClasses=c(
  rep("character",4),rep("numeric",2)
))
rownames(fips_table) <- fips_table$Alpha.code

p0list <- list()
# New facet label names 
DeltaDelta.labs <- c("Current Reopening", "Current +25% Reopening")
names(DeltaDelta.labs) <- c("0", "0.25")
mu_Lambda.labs <- c("Testing Rate 1X", "Testing Rate 2X")
names(mu_Lambda.labs) <- c("1", "2")
mu_C.labs <- c("Contact Tracing 1X", "Contact Tracing 2X")
names(mu_C.labs) <- c("1", "2")
out.labs <- c("Daily reported cases","Daily confirmed deaths")
names(out.labs) <- c("positiveIncrease","deathIncrease")


```

## Impact of different scenarios on daily cases and deaths for selected states


```{r scenarioplots current reopening data, echo=FALSE,fig.height=4,fig.width=6}

statesplot <- c("NY","OH","TX","WA")
scen.df <- data.frame(state=sort(rep(statesplot,4)),
                      mu_C = rep(rep(c(1,1,2,2),1),length(statesplot)),
                      mu_Lambda = rep(rep(c(1,2,1,2),1),length(statesplot)),
                      DeltaDelta = rep(rep(0,4),length(statesplot)),
                      stringsAsFactors = FALSE
)
scen.df$scenarioname <- paste("TimeSeries",scen.df$mu_C,scen.df$mu_Lambda,
                              scen.df$DeltaDelta,sep=".")
scen.df$basename <- paste0("SEIR_",scen.df$state,"_",scen.df$scenarioname,".quantiles.csv")
scen.df$scenariodesc <- paste0(scen.df$mu_C,"X Contact Tracing, ",
                               scen.df$mu_Lambda,"X Testing, Current",
                                ifelse(scen.df$DeltaDelta==0.25,
                                       paste0("+",100*scen.df$DeltaDelta,"%"),
                                       ifelse(scen.df$DeltaDelta== -0.25,
                                              paste0(100*scen.df$DeltaDelta,"%"),
                                              "")),
                               " Reopening")

allscendat <-data.frame()
for (k in 1:nrow(scen.df)) {
  scenrow <- scen.df[k,]
  statenow <- scenrow$state
  popnow <- fips_table[statenow,"pop"]
  csvfile <- file.path(folder,statenow,scenrow$basename)
  scendat <- read.csv(csvfile,as.is=TRUE)
  scendat$state <- statenow
  scendat$Output_Var[scendat$Output_Var=="N_pos"] <- "positiveIncrease"
  scendat$Output_Var[scendat$Output_Var=="D_pos"] <- "deathIncrease"
  scendat$Output_Var[scendat$Output_Var=="D_T"] <- "death"
  scendat$Output_Var[scendat$Output_Var=="CumPos"] <- "positive"
  scendat$Date <- as.Date(scendat$Time+60,origin=as.Date(datezero))
  scendat <- subset(scendat,Date>=datadatestart)
  scendat$mu_C <- scenrow$mu_C
  scendat$mu_Lambda <- scenrow$mu_Lambda
  scendat$DeltaDelta <- scenrow$DeltaDelta
  allscendat<-rbind(allscendat,scendat)
}

dummydf <- scen.df
dummydf$Output_Var<-"deathIncrease"
dummydf$Data<-10
dummydf2 <- scen.df
dummydf2$Output_Var<-"positiveIncrease"
dummydf2$Data<-118
dummydf <- rbind(dummydf,dummydf2)
dummydf$Date <- as.Date(preddateend)
```

```{r do plots, echo=FALSE,fig.height=4,fig.width=6}
for (statenow in statesplot) {
  dummy <- subset(dummydf,state==statenow)
  dat.df <- subset(alldat.df,state==statenow)
  obsdat.df<-subset(dat.df,state==statenow & (
    Output_Var == "positiveIncrease" | Output_Var == "deathIncrease"
  )) 
  cumdat.df <- subset(allcumdat.df,state==statenow)
  obsdat.df$Data <- 100000*obsdat.df$Data/fips_table[statenow,"pop"]
  cumdat.df$Data <- 100000*cumdat.df$Data/fips_table[statenow,"pop"]
  obsdat.df<-rbind(obsdat.df,
                   subset(cumdat.df,state==statenow & (
    Output_Var == "positive" | Output_Var == "death"
  )))
  ## DeltaDelta=0
  tmpdat<-subset(allscendat,state == statenow & 
                   (Output_Var=="positiveIncrease" | Output_Var=="deathIncrease") & 
                   DeltaDelta==0 &
                   Date >= datadatestart & 
                   Date <= preddateend)
  #ymax<-max(tmpdat$Prediction.97.5.,10)
  tmpdat$Prediction.2.5. <- 100000*tmpdat$Prediction.2.5./fips_table[statenow,"pop"]
  tmpdat$Prediction.25. <- 100000*tmpdat$Prediction.25./fips_table[statenow,"pop"]
  tmpdat$Prediction.50. <- 100000*tmpdat$Prediction.50./fips_table[statenow,"pop"]
  tmpdat$Prediction.75. <- 100000*tmpdat$Prediction.75./fips_table[statenow,"pop"]
  tmpdat$Prediction.97.5. <- 100000*tmpdat$Prediction.97.5./fips_table[statenow,"pop"]
  rampup.df <- subset(tmpdat,Date==preddateend)
  p0<-ggplot(tmpdat)+
    geom_point(data=dummy,aes(x=Date,y=Data),shape=NA)+
    geom_col(aes(x=Date,y=Data),data=subset(obsdat.df,Output_Var=="positiveIncrease"|
                                              Output_Var=="deathIncrease"))+
    geom_ribbon(aes(x=Date,ymin=Prediction.2.5.,ymax=Prediction.97.5.,
                    fill="CrI"),alpha=0.8)+
    geom_ribbon(aes(x=Date,ymin=Prediction.25.,ymax=Prediction.75.,
                    fill="IQR"),alpha=0.8)+
    geom_line(aes(x=Date,y=Prediction.50.,linetype="Median"))+
    ylab("Daily reported cases or deaths per 100,000")+
    scale_fill_viridis_d(option="magma",begin = 0.6,end=0.95) +
    scale_x_date(date_minor_breaks = "1 week",date_breaks = "month",date_labels = "%b")+
    geom_rect(data=rampup.df,aes(xmin = as.Date("2020-08-01"), xmax = as.Date("2020-08-15"), 
              ymin=0,ymax=Inf,alpha = "Ramp-up period"))+
    scale_alpha_manual(values=0.2)+
    #scale_y_log10(limits=c(1,NA))+
    facet_grid(Output_Var~mu_C+mu_Lambda,scale="free_y",
                  labeller = labeller(mu_C = mu_C.labs,
                                      mu_Lambda = mu_Lambda.labs,
                                      Output_Var = out.labs))+
    guides(linetype = guide_legend(order = 1),fill = guide_legend(order = 2),alpha=guide_legend(order=3))+
          labs(fill="",linetype="Prediction",alpha="")+theme_bw()+theme(legend.position = "bottom")
  print(p0)
  p0list[[statenow]]<-p0+ggtitle(statenow)
}

fig3current<-ggarrange(plotlist=p0list,
                ncol=2,nrow=2,
                common.legend = TRUE,
                legend="bottom",
                labels=c("A","B","C","D"))
ggsave("Fig3ABCDcurrent_07_22-08-15.pdf",plot=fig3current,height=4,width=6,scale=2.5)
ggsave("Fig3ABCDcurrent_07_22-08-15.jpeg",plot=fig3current,height=4,width=6,scale=2.5)
```


```{r scenario Refft, echo=FALSE,fig.height=6,fig.width=15}

preddate<-c("2020-08-15")
fips_table <- read.csv(file.path(folder,"FIPS_TABLE.csv"),colClasses=c(
  rep("character",4),rep("numeric",2)
))
rownames(fips_table) <- fips_table$Alpha.code
statesarr <- fips_table$Alpha.code[2:52]

# New facet label names 
DeltaDelta.labs <- c("Current Reopening", "Current +25% Reopening")
names(DeltaDelta.labs) <- c("0", "0.25")
mu_Lambda.labs <- c("Testing Rate 1X", "Testing Rate 2X")
names(mu_Lambda.labs) <- c("1", "2")
mu_C.labs <- c("Contact Tracing 1X", "Contact Tracing 2X")
names(mu_C.labs) <- c("1", "2")
out.labs <- c("Daily reported cases","Daily confirmed deaths")
names(out.labs) <- c("positiveIncrease","deathIncrease")

scen.df <- data.frame(state=sort(rep(statesarr,12)),
                      mu_C = rep(rep(c(1,1,2,2),3),length(statesarr)),
                      mu_Lambda = rep(rep(c(1,2,1,2),3),length(statesarr)),
                      DeltaDelta = rep(c(rep(0.25,4),rep(0,4),rep(-0.25,4)),length(statesarr)),
                      stringsAsFactors = FALSE
)
scen.df$scenarioname <- paste("TimeSeries",scen.df$mu_C,scen.df$mu_Lambda,
                              scen.df$DeltaDelta,sep=".")
scen.df$basename <- paste0("SEIR_",scen.df$state,"_",scen.df$scenarioname,".quantiles.csv")
scen.df$scenariodesc <- paste0(scen.df$mu_C,"X Contact Tracing, ",
                               scen.df$mu_Lambda,"X Testing, Current",
                                ifelse(scen.df$DeltaDelta==0.25,
                                       paste0("+",100*scen.df$DeltaDelta,"%"),
                                       ifelse(scen.df$DeltaDelta== -0.25,
                                              paste0(100*scen.df$DeltaDelta,"%"),
                                              "")),
                               " Reopening")
scen.df$scenfactor <- factor(scen.df$scenariodesc,
                             levels=rev(head(scen.df$scenariodesc,12)))
allscendat <-data.frame()
for (k in 1:nrow(scen.df)) {
  scenrow <- scen.df[k,]
  statenow <- scenrow$state
  popnow <- fips_table[statenow,"pop"]
  csvfile <- file.path(folder,statenow,scenrow$basename)
  scendat <- read.csv(csvfile,as.is=TRUE)
  scendat$state <- statenow
  scendat$Output_Var[scendat$Output_Var=="N_pos"] <- "positiveIncrease"
  scendat$Output_Var[scendat$Output_Var=="D_pos"] <- "deathIncrease"
  scendat$Output_Var[scendat$Output_Var=="CumDeath"] <- "death"
  scendat$Output_Var[scendat$Output_Var=="CumPosTest"] <- "positive"
  scendat$Date <- as.Date(scendat$Time+60,origin=as.Date(datezero))
  scendat <- subset(scendat,Date==preddate)
  scendat$mu_C <- scenrow$mu_C
  scendat$mu_Lambda <- scenrow$mu_Lambda
  scendat$DeltaDelta <- scenrow$DeltaDelta
  scendat$scenariodesc <- scenrow$scenariodesc
  scendat$scenfactor <- scenrow$scenfactor
  allscendat<-rbind(allscendat,scendat)
}

# ReffRtscendat <- subset(allscendat,(Output_Var == "Refft" |Output_Var == "Rt") & (DeltaDelta<=0 | (mu_C==1 & mu_Lambda==1)))
# ReffRtscendat$R.le.1 <- as.numeric(ReffRtscendat$Prediction.75.<1)
# ReffRtscendat$RefftRt <- as.numeric(ReffRtscendat$Prediction.75.<1)
# p<-ggplot(ReffRtscendat,aes(state,scenfactor))+geom_tile(aes(fill=(R.le.1==1)))+
#   scale_fill_viridis_d(option="magma")+labs(fill=bquote(paste("IQR of ",R[eff](t)<1)))+
#   theme(legend.position = "bottom")
# print(p)


Reffscendat <- subset(allscendat,Output_Var == "Refft" & (DeltaDelta<=0 | (mu_C==1 & mu_Lambda==1)))
Reffscendat$R.le.1 <- as.numeric(Reffscendat$Prediction.75.<1)
p<-ggplot(Reffscendat,aes(state,scenfactor))+geom_tile(aes(fill=(R.le.1==1)))+
  scale_fill_viridis_d(option="magma")+labs(fill=bquote(paste("IQR of ",R[eff](t)<1)))+
  theme(legend.position = "bottom")
print(p)
#ggsave("heatmap.pdf",p,height=5,width=15)
```

```{r scenario grades,fig.height=6,fig.width=8}

Reffscendat.wide<-spread(Reffscendat[,c("state","scenfactor","R.le.1")],scenfactor,R.le.1)
Grade.df <- data.frame(state=Reffscendat.wide$state)
Grade.df$value<-"Very High"

### Very Low = can reopen > 25%
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==1] <- "Very Low"
### Low = can reopen < 25%
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==1] <- "Low"
### Moderate = can reopen with testing
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
                  Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==1] <- "Moderate"
### High = can reopen with contact tracing, or sheltering, but not with testing
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==0 &
                  (Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==1 |
                    Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current-25% Reopening`==1)] <- "High"
### Very high = everything else
Grade.df$value <- factor(Grade.df$value,levels=
                           c("Very Low","Low","Moderate","High","Very High"))


# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==1] <- "None"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==1] <- "Low"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
#                  (Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==1 |
#                     Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==1)] <- "Moderate"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
#                  (Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==0 &
#                     Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==0) &
#                  (Reffscendat.wide$`2X Contact Tracing, 2X Testing, Current Reopening`==1 |
#                     Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current-25% Reopening`==1)] <- "High"
# Grade.df$value <- factor(Grade.df$value,levels=
#                            c("None","Low","Moderate","High","Very High"))

Reffscendat.mat<-as.matrix(Reffscendat.wide[,-1])
rownames(Reffscendat.mat)<-Reffscendat.wide[,1]
heatmap(t(Reffscendat.mat),cexRow = 0.5,cexCol = 0.5)
Reffscendat$stateorder <- factor(Reffscendat$state,
                                 levels=Grade.df$state[order(Grade.df$value)])
porder<-ggplot(Reffscendat,aes(stateorder,scenfactor))+geom_tile(aes(fill=(R.le.1==1)))+
  scale_fill_viridis_d(option="magma")
#ggsave("heatmaporder.pdf",porder,height=5,width=15)




pusa<-plot_usmap(data = Grade.df, values = "value") + 
  scale_fill_viridis_d(name = "Mitigation Need", option="magma",direction=-1,begin=0.35) + 
  theme(legend.position = "right")
print(pusa)
# ggsave("Fig5A_MitigationNeed.pdf",plot=pusa,height=4,width=6)
# ggsave("Fig5A_MitigationNeed.jpeg",plot=pusa,height=4,width=6)
# 
# write.csv(x = Grade.df,file="MitigationGrades.csv",row.names = FALSE)
```


```{r scenario Rt, echo=FALSE,fig.height=4,fig.width=15}


preddate<-c("2020-08-15")
fips_table <- read.csv(file.path(folder,"FIPS_TABLE.csv"),colClasses=c(
  rep("character",4),rep("numeric",2)
))
rownames(fips_table) <- fips_table$Alpha.code
statesarr <- fips_table$Alpha.code[2:52]

# New facet label names 
DeltaDelta.labs <- c("Current Reopening", "Current +25% Reopening")
names(DeltaDelta.labs) <- c("0", "0.25")
mu_Lambda.labs <- c("Testing Rate 1X", "Testing Rate 2X")
names(mu_Lambda.labs) <- c("1", "2")
mu_C.labs <- c("Contact Tracing 1X", "Contact Tracing 2X")
names(mu_C.labs) <- c("1", "2")
out.labs <- c("Daily reported cases","Daily confirmed deaths")
names(out.labs) <- c("positiveIncrease","deathIncrease")

scen.df <- data.frame(state=sort(rep(statesarr,12)),
                      mu_C = rep(rep(c(1,1,2,2),3),length(statesarr)),
                      mu_Lambda = rep(rep(c(1,2,1,2),3),length(statesarr)),
                      DeltaDelta = rep(c(rep(0.25,4),rep(0,4),rep(-0.25,4)),length(statesarr)),
                      stringsAsFactors = FALSE
)
scen.df$scenarioname <- paste("TimeSeries",scen.df$mu_C,scen.df$mu_Lambda,
                              scen.df$DeltaDelta,sep=".")
scen.df$basename <- paste0("SEIR_",scen.df$state,"_",scen.df$scenarioname,".quantiles.csv")
scen.df$scenariodesc <- paste0(scen.df$mu_C,"X Contact Tracing, ",
                               scen.df$mu_Lambda,"X Testing, Current",
                                ifelse(scen.df$DeltaDelta==0.25,
                                       paste0("+",100*scen.df$DeltaDelta,"%"),
                                       ifelse(scen.df$DeltaDelta== -0.25,
                                              paste0(100*scen.df$DeltaDelta,"%"),
                                              "")),
                               " Reopening")
scen.df$scenfactor <- factor(scen.df$scenariodesc,
                             levels=rev(head(scen.df$scenariodesc,12)))
allscendat <-data.frame()
for (k in 1:nrow(scen.df)) {
  scenrow <- scen.df[k,]
  statenow <- scenrow$state
  popnow <- fips_table[statenow,"pop"]
  csvfile <- file.path(folder,statenow,scenrow$basename)
  scendat <- read.csv(csvfile,as.is=TRUE)
  scendat$state <- statenow
  scendat$Output_Var[scendat$Output_Var=="N_pos"] <- "positiveIncrease"
  scendat$Output_Var[scendat$Output_Var=="D_pos"] <- "deathIncrease"
  scendat$Output_Var[scendat$Output_Var=="CumDeath"] <- "death"
  scendat$Output_Var[scendat$Output_Var=="CumPosTest"] <- "positive"
  scendat$Date <- as.Date(scendat$Time+60,origin=as.Date(datezero))
  scendat <- subset(scendat,Date==preddate)
  scendat$mu_C <- scenrow$mu_C
  scendat$mu_Lambda <- scenrow$mu_Lambda
  scendat$DeltaDelta <- scenrow$DeltaDelta
  scendat$scenariodesc <- scenrow$scenariodesc
  scendat$scenfactor <- scenrow$scenfactor
  allscendat<-rbind(allscendat,scendat)
}

Reffscendat <- subset(allscendat,Output_Var == "Rt" & (DeltaDelta<=0 | (mu_C==1 & mu_Lambda==1)))
Reffscendat$R.le.1 <- as.numeric(Reffscendat$Prediction.75.<1)
p<-ggplot(Reffscendat,aes(state,scenfactor))+geom_tile(aes(fill=(R.le.1==1)))+
  scale_fill_viridis_d(option="magma")+labs(fill=bquote(paste("IQR of ",R[eff](t)<1)))+
  theme(legend.position = "bottom")
print(p)
ggsave("Rtheatmap.pdf",p,height=5,width=15)
```


```{r scenario map Rt, echo=FALSE,fig.height=6,fig.width=8}
Reffscendat.wide<-spread(Reffscendat[,c("state","scenfactor","R.le.1")],scenfactor,R.le.1)
Grade.df <- data.frame(state=Reffscendat.wide$state)
Grade.df$value<-"Very High"
### Very Low = can reopen > 25%
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==1] <- "Very Low"
### Low = can reopen < 25% with testing
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 (Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==1 |
                    Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==1)] <- "Low"
### Moderate = need tracing or sheltering
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
                  Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==0 &
                 (Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==1 |
                    Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current-25% Reopening`==1)
                  ] <- "Moderate"
### High = can reopen with multiple interventions of contact tracing, testing, and/or sheltering,
Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
                 Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==0 &
                 Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==0 &
                    Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current-25% Reopening`==0 &
                  (Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current-25% Reopening`==1 |
                     Reffscendat.wide$`2X Contact Tracing, 2X Testing, Current Reopening`==1 |
                     Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current-25% Reopening`==1 |
                     Reffscendat.wide$`2X Contact Tracing, 2X Testing, Current-25% Reopening`==1)] <- "High"
### Very high = everything else
Grade.df$value <- factor(Grade.df$value,levels=
                           c("Very Low","Low","Moderate","High","Very High"))
# 
# 
# 
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==1] <- "None"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==1] <- "Low"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
#                  (Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==1 | 
#                     Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==1)] <- "Moderate"
# Grade.df$value[Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current+25% Reopening`==0 &
#                  Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current Reopening`==0 &
#                  (Reffscendat.wide$`1X Contact Tracing, 2X Testing, Current Reopening`==0 & 
#                     Reffscendat.wide$`2X Contact Tracing, 1X Testing, Current Reopening`==0) &
#                  (Reffscendat.wide$`2X Contact Tracing, 2X Testing, Current Reopening`==1 |
#                     Reffscendat.wide$`1X Contact Tracing, 1X Testing, Current-25% Reopening`==1)] <- "High"
# Grade.df$value <- factor(Grade.df$value,levels=
#                            c("None","Low","Moderate","High","Very High"))
Reffscendat.mat<-as.matrix(Reffscendat.wide[,-1])
rownames(Reffscendat.mat)<-Reffscendat.wide[,1]
heatmap(t(Reffscendat.mat),cexRow = 0.5,cexCol = 0.5)
Reffscendat$stateorder <- factor(Reffscendat$state,
                                 levels=Grade.df$state[order(Grade.df$value)])
porder<-ggplot(Reffscendat,aes(stateorder,scenfactor))+geom_tile(aes(fill=(R.le.1==1)))+
  scale_fill_viridis_d(option="magma")
#ggsave("heatmaporder.pdf",porder,height=5,width=15)




pusa<-plot_usmap(data = Grade.df, values = "value") + 
  scale_fill_viridis_d(name = "Mitigation Need\nJuly 22, 2020", option="magma",direction=-1,begin=0.35) + 
  theme(legend.position = "right")
print(pusa)
ggsave("Fig5_RtMitigationNeed.pdf",plot=pusa,height=4,width=6)
ggsave("Fig5_RtMitigationNeed.jpeg",plot=pusa,height=4,width=6)

write.csv(x = Grade.df,file="RtMitigationGrades.csv",row.names = FALSE)
```